#eureka:
 # instance:
  #  hostname: localhost
server:
  port: 7072
  
spring:
  application:
    name: course-service
  datasource:
    password: mani
    url: jdbc:mysql://localhost:3306/pip
    username: root
  jpa:
    hibernate:
      ddl-auto: update
